# Generated by Django 6.0.4 on 2026-04-15 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('in_progress', 'in Progress'), ('done', 'Done')], default='pendente', max_length=20),
        ),
    ]
