# Generated by Django 6.0.4 on 2026-04-15 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_priority_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority_int',
            field=models.IntegerField(choices=[(1, 'Baixa'), (2, 'Media'), (3, 'Alta')], default=2),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[(1, 'Baixa'), (2, 'Media'), (3, 'Alta')], default=2, max_length=10),
        ),
    ]
