# Generated by Django 6.0.4 on 2026-04-15 18:43
from django.db import migrations

def migrate_priority(apps, schema_editor):
    Task = apps.get_model('tasks', 'Task')

    for task in Task.objects.all():
        if task.priority == 'baixa':
            task.priority_int = 1
        elif task.priority == 'media':
            task.priority_int = 2
        elif task.priority == 'alta':
            task.priority_int = 3
        task.save()

class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_priority_int_alter_task_priority'),
    ]

    operations = [
        migrations.RunPython(migrate_priority),
    ]
