# Generated by Django 6.0.4 on 2026-04-15 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_rename_update_at_task_updated_at'),
        ('tasks', '0006_auto_20260415_1543'),
    ]

    operations = [
    ]
