# Generated by Django 6.0.4 on 2026-04-15 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_merge_20260415_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='priority',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='priority_int',
            new_name='priority',
        ),
    ]
